### ISSUE TITLE
incorrect project count

### ISSUE THREAD

**Issue by zayoon013** [GenericProgrammer1234/Pyratch#16]
When I open my page it shows I have only 60 projects but I have 100

<img width="1280" alt="Screen Shot 2023-08-27 at 14 23 32" src="https://github.com/GenericProgrammer1234/Pyratch/assets/125116818/46edb01d-1c84-4e0e-ab36-fac717e51e15">

**Comment by GenericProgrammer1234** [comment]
Hmm, interesting, will fix.

**Comment by GenericProgrammer1234** [comment]
Make sure you are using the latest scratchattach version and are on the latest version of Pyratch.
